name: Deploy Website

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install Go packages
        run: |
          cd backend/GPT
          go mod vendor

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          cd ../spacy
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      # Frontend setup
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"

      - name: Install frontend packages and build
        run: |
          cd frontend
          bun install
          bun run build  # Ensure you have a build script in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
